POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Node.js"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/ba59f2df-bc67-405d-bf34-872137d7e483